apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: github-nodeapp
  namespace: github-app
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "4"
    spec:
      serviceAccountName: knative-gcr-imagepull-sa
      containers:
        - image: asia.gcr.io/knativelocal/nodeapp
          ports:
            - containerPort: 8080