apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: github-nodeapp
  namespace: github-deployment
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "4"
    spec:
      serviceAccountName: knative-gcr-imagepull
      containers:
        - image: "asia.gcr.io/knativelocal/nodeapp:latest"
          ports:
            - containerPort: 8080