apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: holaapp
  namespace: knativeapps
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "4"
    spec:
      serviceAccountName: knative-pull-images
      containers:
        - image: ""
          ports:
            - containerPort: 8080